### PR TITLE
BUGFIX: Backwards compatibility for image factory

### PR DESCRIPTION
**Pull request by kitsunet**

### CODE REVIEW

**Comment by kitsunet** [comment]
I don't care about style CI atm, it's not even a file I touched.

**Review by kdambekalns — COMMENTED** [review]
Yup. Somehow weird, since the enabledDrivers is always there, because it comes with the package, but…

That setup issue is caused by setup doing something wrong, IMHO.

**Comment by kitsunet** [comment]
It is, but this here is much easier to fix for now. This is not a final fix, just something to make it work quickly.

**Review by gerhard-boden — APPROVED** [review]

**Comment by gerhard-boden** [comment]
Should we put a special label or something on hotfixes? Would be nice to somehow see what was repaired with hotfixes, so someone can work on a better solution when there is more time.

**Comment by kitsunet** [comment]
I added a FIXME comment :)

**Comment by gerhard-boden** [comment]
Hehe, thanks! Guess that's the only reasonable way to do it. Just checked how many of those we have in Flow / Neos, but with 12 (Flow) and respectively 23 (Neos) matches it's a surprisingly small number

**Comment by kdambekalns** [comment]
👍

**Pull request merged**
